### ISSUE TITLE
Krappe uitlijning

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#141]
Dit zal aan dat nieuwe template liggen ofzo, maar sommige dingen staan wel heel strak tegen de rand van het window uitgelijnd, bijvoorbeeld de sol en de titels:
<img width="923" alt="Screenshot 2024-07-17 at 13 57 51" src="https://github.com/user-attachments/assets/1f425bec-32fb-4e85-9fbd-511bbe2b0f1f">
<img width="1403" alt="Screenshot 2024-07-17 at 13 54 04" src="https://github.com/user-attachments/assets/52ec370e-5f13-4e38-97e8-e49ca350faa5">

Geeft een beetje een opgesloten gevoel. Het is bij het pp-gedeelte gelukkig niet zo.

**Comment by tymees** [comment]
Ja dit heeft idd met de nieuwe template te maken. (Nouja, onze nieuwe UI library). 

De admin gebruikt een andere standaard breedte dan normaal, wat voor wat problemen zorgt...

Voor mezelf, deze patch moet toegevoegd worden aan de app-css:

```css
@media (max-width: 100rem) {
  .uu-root-container .uu-unified-header, .uu-root-container .uu-hero, .uu-root-container .uu-cover .uu-cover-hero  {
    padding-left: var(--bs-uu-container-padding-x) !important;
    padding-right: var(--bs-uu-container-padding-x) !important;
  }
}
```
